# Generated by Django 5.0.1 on 2024-02-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_rename_menuitem_cart_item_alter_cart_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_crew',
            new_name='delivery_crew_user',
        ),
    ]
